### ISSUE TITLE
ERR! 

### ISSUE THREAD

**Issue by moorlag** [r-rayns/inky_dash#12]
After following the manual in the readme. This is the output I am getting. 
I've updated the Pi Zero, the Inky Phat does work with the vendor-supplied Python scripts. 
I'm a little out of my league, any pointers, tips?  

```
pi@inkyphat:~ $ npm start
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-08-07T13_50_52_566Z-debug.log
```

**Comment by r-rayns** [comment]
Ah, looks like my readme is misleading! Try this instead:
1. Make sure you are in the root of the project directory, in your case this would probably be `/home/pi/inky_dash_v1.0.0`
2. Run `node app.js`, that should then work.

I'll update the readme, thanks for finding this! Let me know if it works or you need any other assistance.

---------------------------
_The reason for your error is that there is no `package.json` file in the directory where you are executing `npm start`. The `package.json` file tells NPM how to "start". However this is a red herring as there is no `package.json` in the project root either (though my readme would seem to suggest there is)!_

**Comment by moorlag** [comment]
Thanks for the very quick response
the web interface is loading! See the attached picture. I tried to upload the image. 
It does work... but the e-paper screen isn't updating. 

<img width="911" alt="Schermafbeelding 2020-08-07 om 22 22 53" src="https://user-images.githubusercontent.com/2832006/89685469-b055e980-d8fc-11ea-9f35-1e50b37df491.png">
![Naamloos](https://user-images.githubusercontent.com/2832006/89686371-8ef5fd00-d8fe-11ea-8adb-3e4b489aea8b.png)

**Comment by r-rayns** [comment]
Running `node app.js` on the Pi, can you see any output on the Pi Zero's terminal when you try to upload an image? Errors should get logged to there.

--------

You can also test the actual Python script that changes the display:
```bash
cd /home/pi/inky_dash_v1.0.0/python_scripts/
python display-current-image.py 'red' 'black'
```
That will bypass everything and just load whatever image is located in `/home/pi/inky_dash_v1.0.0/current_image/inky.png`

**Comment by moorlag** [comment]
__holiday update__

I've tried:
`node app.js`

```
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '/home/pi/inky_dash_v1.0.0/python-scripts/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

```
**cd /home/pi/inky_dash_v1.0.0/python_scripts/
python display-current-image.py 'red' 'black'**
```
resulted in 
`cannot reshape array of size 17384 into shape (104,212)`

**Comment by r-rayns** [comment]
First error is because node couldn't find `app.js` in the directory `/home/pi/inky_dash_v1.0.0/python-scripts/`. You need to be in the directory above when you run `node app.js` which would be `/home/pi/inky_dash_v1.0.0/`. 

Regardless I think I can see the problem from the output you got when running the python script. The error `cannot reshape array of size 17384 into shape (104,212)` I believe is a result of the image not being in the format supported by the Inky pHAT display. The format is :
- 212px wide & 104px high
- using white, black and red (or yellow depending on your display) colour palette
- saved as a PNG

Even if it looks like you are only using the three accepted colours, the image could still be using a RGB colourspace. You can create an image in the correct format quite easily with [GIMP](https://www.gimp.org/). I've taken some screenshots of the process:

1. Create a new image with width 212 and height 104
![new_image0](https://user-images.githubusercontent.com/3247680/90442934-54951880-e0d3-11ea-8b73-8107eb6f575f.png)

2. Create a new palette with your three colours (black, white & red/yellow)
![new_image1](https://user-images.githubusercontent.com/3247680/90443481-3b409c00-e0d4-11ea-816f-314457a8b778.png)

3. Now add your image
![new_image2](https://user-images.githubusercontent.com/3247680/90443531-4f849900-e0d4-11ea-904b-fe29c10a11aa.png)

4. Select Image > Mode > Indexed... 
![new_image3](https://user-images.githubusercontent.com/3247680/90443568-61fed280-e0d4-11ea-9c3a-bbc18732b2bc.png)

5. Select the palette you created in step 2 as a custom palette
![new_image4](https://user-images.githubusercontent.com/3247680/90443665-8490eb80-e0d4-11ea-95ba-5530dc68814c.png)

6. Finally apply the palette and save your image as a PNG. Hopefully that should work.
![new_image5](https://user-images.githubusercontent.com/3247680/90443704-98d4e880-e0d4-11ea-87e7-c5600de2a003.png)

**Comment by moorlag** [comment]
Thanks for the extensive response! 

It now all works. Anything else in the pipe line?

**Comment by r-rayns** [comment]
Brilliant! No problem, it's nice to have someone use something you built. I may add a slide-show ability at some point.
